### ISSUE TITLE
Integration with V8 engine

### ISSUE THREAD

**Issue by fdarie** [sq/JSIL#1020]
Hi
I was wondering whether is possible to load the generated Java Script along with JSIL libraries into the **V8 engine without having any browser**.

My scenario is this: C# code is transformed into JS (no DOM interaction) and then try to feed the generated Java scripts into V8 engine runtime.  At the runtime, Java Script is assumed to interact with Java code by using V8 Java registered callbacks. 

Thank you

**Comment by kg** [comment]
Yes, JSIL supports running outside of a browser by specifying a different environment in your config. This is used for the automated tests.

On October 11, 2016 2:59:36 PM PDT, Florin Darie <notifications@github.com> wrote:
>Hi
>I was wondering whether is possible to load the generated Java Script
>along with JSIL libraries into the **V8 engine without having any
>browser**.
>
>My scenario is this: C# code is transformed into JS (no DOM
>interaction) and then try to feed the generated Java scripts into V8
>engine runtime.  At the runtime, Java Script is assumed to interact
>with Java code by using V8 Java registered callbacks. 
>
>Thank you
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/sq/JSIL/issues/1020

- kg (mobile)
