### ISSUE TITLE
[Q] Resources support?

### ISSUE THREAD

**Issue by 0xFireball** [sq/JSIL#1023]
Is there an easy way to load an embedded resource with JSIL? The `GetCallingAssembly()` (I need to load the resource from the caller in a library method) is not implemented in JSIL. I have noticed that JSIL compiles RESX files to RESJ files. I want to embed a XML file as an embedded resource and load it at runtime. How can I accomplish this or something similar?

Thanks for the help!

**Comment by kg** [comment]
```GetCallingAssembly``` is impossible to implement in JS because it doesn't offer stack-walking. You can get the executing assembly, however, or extract an Assembly from a type object.

**Comment by 0xFireball** [comment]
Thanks, resource loading works now. I now have an error about a not-implemented SelectMany call. I'll try to look into it myself.
