### ISSUE TITLE
Installing JSIL on Linux

### ISSUE THREAD

**Issue by marcelo-rocha** [sq/JSIL#1048]
I'm trying to install JSIL on a Ubuntu 16.04 running at WSL(Windows Subsystem for Linux). When I run the script **linux-build.sh** it runs the script **install-pcl-reference.sh**, and this script trys to download  PCL assemblies from http://storage.bos.xamarin.com/bot-provisioning/PortableReferenceAssemblies-2014-04-14.zip but it fails, because the server is not responding. There are another website where I can download that assembly?

**Comment by kg** [comment]
I'm sorry, I don't know. It looks like Microsoft distributes PCL reference assemblies now that can be used with Mono, so investigating that might be a good step.

**Comment by marcelo-rocha** [comment]
I had success installing the latest version of Mono and disabling the downloading of PCL.
