### ISSUE TITLE
How to Convert a CSharp Project to JavaScript on a Mac?

### ISSUE THREAD

**Issue by lancejpollard** [sq/JSIL#1057]
Hi there, I would like to convert [this](https://github.com/roice3/MagicTile) to JavaScript, but I am on a Mac and as far as I can tell this tool JSIL [only works on Windows](https://github.com/sq/JSIL/wiki). Am I wrong about that? How can I convert a CSharp project like the linked one (with dozens of files and imports) on a Mac to JavaScript?

Thanks!

**Comment by electricessence** [comment]
Is there a specific reason?
3 suggestions:

1. Don't.
2. Migrate slowly using TypeScript.
3. See if you can add on a Blazor app and then leverage the C# natively using Blazor/WebAssembly.

**Comment by kg** [comment]
JSIL is fully compatible with mono and the sandbox on the website is running on a Linux server. However, the project is unmaintained so I wouldn't advise using it.
