### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by davideurbani** [sq/JSIL#131]
[Is it possible][/[Does someone tryed] to compile and port a Windows Forms application?
Are there a working example of WinForms app?

Thank you all.
Davide Urbani

**Comment by 0xFireball** [comment]
what do we use now for XNA, as it is no longer officially supported and i have no idea how to install it on VS2015

**Comment by iskiselev** [comment]
As I remember, [community repack of XNA](https://mxa.codeplex.com/releases/view/618279) works with VS 2015.
