### ISSUE TITLE
jQuery wrapper and/or samples

### ISSUE THREAD

**Issue by lostmsu** [sq/JSIL#132]
A strongly typed jQuery wrapper or at least samples of how to use jQuery (selectors, events and DOM manipulation) would be great to have and stimulate web developers to use JSIL.

**Comment by 0xFireball** [comment]
Hello! in case this is still relevant, I am trying to extend JSIL.Hacks! Thanks for the work @markusjohnsson!

https://github.com/exaphaser/ExaPhaser.WebForms

**Comment by markusjohnsson** [comment]
You are welcome to use any code in JSIL.Hacks, however, I don't think I've touched it since my last comment (from 2012, OMG!) and I doubt anything works in there.

**Comment by 0xFireball** [comment]
Your DOM Element bindings have been extremely useful! I updated them and added more, as well as some more managed JavaScript wrappers. Your MVVM features have been extremely helpful, and I am currently working on a GUI framework built with HTML5/JS.

https://github.com/exaphaser/ExaPhaser.SharpJS

There's another company developing with JSIL: http://www.cshtml5.com
However, they are commercializing it and it is closed source. It claims to be able to run XAML apps with JSIL.
