### ISSUE TITLE
ObservableCollection<string> not working but List<string> is working

### ISSUE THREAD

**Issue by Alphapage** [sq/JSIL#288]
Hello,
I'd like to use ObservableCollection<string> instead of List<string> to get changed notifications easily, but it doesn't seems to work.
Here is my little test case:
System.Collections.ObjectModel.ObservableCollection<string> obs = new System.Collections.ObjectModel.ObservableCollection<string>() { "str1", "str2" };
            obs.Add("str3");
            System.Diagnostics.Debug.WriteLine("count obs:" + obs.Count);
            System.Collections.Generic.List<string> list = new System.Collections.Generic.List<string>() { "str1", "str2" };
            list.Add("str3");
            System.Diagnostics.Debug.WriteLine("count list:" + list.Count);

Thanks in advance for your help.

**Comment by wklingler** [comment]
Why was this closed?  I see some possible workarounds but ObservableCollections still do not work with JSIL.

**Comment by iskiselev** [comment]
Issue was closed by original reporter. `ObservableCollections` is not implemented in JSIL bootstrap. However, I believe it should work with translated BCL (System assembly).

**Comment by kg** [comment]
If it doesn't work in translated BCL, definitely file an issue about that.
