### ISSUE TITLE
GetHashCode() for Int64 should be implemented

### ISSUE THREAD

**Issue by iskiselev** [sq/JSIL#325]
There is no implementation of GetHashCode() in Int64, so Object GetHashCode() implementaion is used and each instance has different value.
Here is test case:
```
class Program {
    public static void Main ()
    {
        long i1 = 1;
        long i2 = 1;
        System.Console.WriteLine(i1.GetHashCode() == i2.GetHashCode() ? "true" : "false"); // .NET prints an empty line, JSIL prints "null"
    }
}
```

It could be fixed with such addition to JSIL.Bootstrap.Int64.js:
```
    $.Method({ Static: false, Public: true }, "GetHashCode",
    (new JSIL.MethodSignature($.Int32, [], [])),
    function () {
        return this.ToInt32();
    });
```

**Comment by markusjohnsson** [comment]
I think GetHashCode should only use the lower 32 bits of the long value. I don't think ToInt32 does a very good job there.. Try something like
 
```
return this.a | ((this.b & 0xff) << 8);
```

**Comment by kg** [comment]
Thanks @markusjohnsson, your suggestion seems fine.
