### ISSUE TITLE
Error with FirstOrDefault

### ISSUE THREAD

**Issue by elw00d** [sq/JSIL#380]
> Error: The external method '!!0 FirstOrDefault<TSource> (System.Collections.Generic.IEnumerable`1[!!0], System.Func`2[!!0, System.Boolean])' of type 'System.Linq.Enumerable' has not been implemented.
    at Object.ExternalMemberStub [as FirstOrDefault$b1$320[!!0],442[!!0,8]=!!0] (file:///D:/all/ConsoleFramework/Web/TestApp/TestApp/bin/Libraries/JSIL.Core.js:1245:17)
    at MethodSignature_CallStatic$1$2 [as CallStatic] (jsil://closure/MethodSignature.CallStatic$1$2:11:19)
    at Function.EventManager_AddHandler$01 (file:///D:/all/ConsoleFramework/Web/TestApp/TestApp/bin/Debug/ConsoleFramework,%20Version=1.0.0.0,%20Culture=neutral,%20PublicKeyToken=null.js:4160:31)
    at Function.ConsoleFramework_Events_EventManager_AddHandler (jsil://closure/ConsoleFramework.Events.EventManager.AddHandler:10:23)
    at Function.EventManager_AddHandler$00 

Original code is:

```
private class DelegateInfo {
            public readonly Delegate @delegate;
            public readonly bool handledEventsToo;

            public DelegateInfo(Delegate @delegate, bool handledEventsToo) {
                this.@delegate = @delegate;
                this.handledEventsToo = handledEventsToo;
            }
        }
...
private class RoutedEventTargetInfo {
            public readonly object target;
            public List<DelegateInfo> handlersList;

            public RoutedEventTargetInfo(object target) {
                if (null == target)
                    throw new ArgumentNullException("target");
                this.target = target;
            }
        }
...
RoutedEventInfo routedEventInfo = routedEvents[key];
            bool needAddTarget = true;
            if (routedEventInfo.targetsList != null) {
                RoutedEventTargetInfo targetInfo = routedEventInfo.targetsList.FirstOrDefault(info => info.target == target);
                if (null != targetInfo) {
                    if (targetInfo.handlersList == null)
                        targetInfo.handlersList = new List<DelegateInfo>();
                    targetInfo.handlersList.Add(new DelegateInfo(handler, handledEventsToo));
                    needAddTarget = false;
                }
            }
```

Generated js is

```
var routedEventInfo = $thisType.routedEvents.get_Item(key);
    var needAddTarget = true;
    if (routedEventInfo.targetsList !== null) {
      var targetInfo = $S06().CallStatic($T0F(), "FirstOrDefault$b1", [$asm01.ConsoleFramework.Events.EventManager_RoutedEventTargetInfo], routedEventInfo.targetsList, function (info) {
          return (info.target === this.target);
        }.bind($closure0));
      if (null !== targetInfo) {
```

I failed to provide a simplified code demo, because all simple attempts worked fine.

**Comment by iskiselev** [comment]
Also adding system assemblies in .jsilconfig Redirect should also solve this problem.
Something like (but for all used .Net Framework assemblies):
```
"Assemblies" : {
"Redirects": {
  "mscorlib" : "mscorlib, Version=4.0.0.0" 
} }
```

**Comment by elw00d** [comment]
Thanks, will try it, now I'm just using 4.0 everywhere :smile_cat:
