### ISSUE TITLE
Incorrect generic type resolution

### ISSUE THREAD

**Issue by iskiselev** [sq/JSIL#479]
Next test case demonstrate error:
```
using System;
using JSIL;

public static class Program
{
    public static void Main()
    {
        Write(typeof (Derived<>).GetField("Field").FieldType);
        Write(typeof (Derived<SomeClass>).GetField("Field").FieldType);
    }

    public static void Write(Type type)
    {
        Console.WriteLine("ContainsGenericParameters: {0}",
                          !Builtins.IsJavascript
                              ? type.ContainsGenericParameters
                              : Verbatim.Expression(@"type.__IsClosed__ === false"));
    }
}

public class Derived<V>
{
    public G<G<V>> Field;
}

public class G<T> { }

public class SomeClass { }
```

When we run it, both `typeof (Derived<>).GetField("Field").FieldType` and `typeof (Derived<>).GetField("Field").FieldType` have `__IsClosed__ = false`, which is unexpected for second case.

If in the same test, if we run only second test, `typeof (Derived<>).GetField("Field").FieldType`, then `__IsClosed__=true`.

**Comment by iskiselev** [comment]
Looks I've understand it and fix it.
When Derived<> initialized, it replaces TypeRef on it's members with constructed types.
Derived<SomeClass> later use members of Derived<> to build own member list. If Derived<> has some partial open types, we have a problem.
Fix is very easy:
```
 JSIL.$ResolveGenericTypeReferenceInternal = function (obj, context) {
+  if ((typeof (obj) === "function")) {
+    obj = obj.__Type__;
+  }
+
   if ((typeof (obj) !== "object") || (obj === null))
     return null;
```

So, we should before check get Type object from partial type, so we can construct closed generic here if it was open (there was already such check).

**Comment by kg** [comment]
Hmmm, that makes sense.
