### ISSUE TITLE
FieldInfo.SetValue error

### ISSUE THREAD

**Issue by TriEdgeAI** [sq/JSIL#644]
I have the following code:

	object o = Activator.CreateInstance(type);	
	FieldInfo[] fields = type.GetFields();

	for(int i = 0; i < fields.Length; i++)
	{
		fields[i].SetValue(o, ...);
	}

It gets translated to:

	var o = $S0B().CallStatic($T17(), "CreateInstance", null, type);
	var fields = type.GetFields();
	
	for (i = 0; i < (fields.length | 0); i = ((i + 1) | 0))
	{
	          (fields[i]).SetValue(o, ...);
	));

Which seems correct and all, but suddenly:

	Uncaught TypeError: undefined is not a function

I was only able to find out that this is caused by FieldInfo.SetValue, which is undefined.
Any workarounds for this?

**Comment by TriEdgeAI** [comment]
I added the following code in JSIL.Core.Reflection.js right below the implementation of GetValue in order to solve my problem (not sure if it's a legit solution, but I'm posting it just in case someone else comes across this):

		$.Method({Static:false, Public:true, Virtual:true }, "SetValue",
		  (new JSIL.MethodSignature($.Object, [$.Object, $.Object], [])),
		  function SetValue (obj, value) {
			if (this.IsStatic) {
			  this.DeclaringType.__PublicInterface__[this._descriptor.Name] = value;
			  return;
			}

			if (obj === null) {
			  throw new System.Exception("Non-static field requires a target.");
			}

			if (!this.DeclaringType.IsAssignableFrom(obj.__ThisType__)) {
			  throw new System.Exception("Field is not defined on the target object.");
			}

			obj[this._descriptor.Name] = value;
		  }
		);

**Comment by kg** [comment]
Yeah, I probably never implemented SetValue. Your implementation looks good.

**Comment by TriEdgeAI** [comment]
Also, I noticed Array.SetValue is missing (probably Array.GetValue, too), but I worked it around with a quick Verbatim.Expression instead :grin:

**Comment by kg** [comment]
There's a specific reason why the array.setvalue/getvalue methods are missing, if memory serves - the whole .NET type system when it comes to arrays is a trainwreck. Array types are *really* weird.

Verbatim is probably the ticket there, but it won't interact properly with packed arrays... Do you mind filing a separate issue about array.setvalue/array.getvalue?

**Comment by kg** [comment]
Lemme know if my version of your fix is sufficient.

**Comment by TriEdgeAI** [comment]
Looks just about right, imho.
