### ISSUE TITLE
Unable to swap value of params

### ISSUE THREAD

**Issue by dbh1997** [sq/JSIL#667]
public class Sample
        {
            public static void Func(int a, int b)
            {
                if (a > b)
                {
                    int swap = a;
                    //Console.WriteLine("swap = {0}", swap);
                    a = b;
                    b = swap;
                }
                Console.WriteLine("a = {0}", a);
                Console.WriteLine("b = {0}", b);
            }
        }

        public static void Run()
        {
            Sample.Func(6,5); 
        }

Results in 5 and 5.  Here's the good part though.  Add the commented out line to write the value of swap, and then it shows 5 and 6 as expected.

- static doesn't matter
- name of swap variable doesn't matter
- still broken with if statement removed, so it doesn't come into play
- reversing order (i.e. swap = b, b=a, a=swap) also breaks (values are both 6)
- Replacing the WrieLine with swap=swap+1-1 also works, although I wouldn't trust the optimizer to not get rid of it.  Basically anything that accesses the swap value prior to it being used to assign back the value seems to snap it out of the problem.

I would consider this one pretty bad defect compared to most of the others.  I've seen other places where I've had to add magic extra accesses before things work but was never able to boil it down to a simple case until now.

**Comment by kg** [comment]
Probably the static analyzer. Odd that this doesn't work, I thought I had a test case for it...

**Comment by kg** [comment]
OK I figured out why this wasn't caught by the tests. It specifically applies to swapping parameters (locals work correctly). That should make it pretty easy to fix... thanks.

**Comment by kg** [comment]
Should be fixed. Yell at me if it isn't. Thanks for reporting.

**Comment by dbh1997** [comment]
Tested with fix, seems to work fine.  Thanks!
