### ISSUE TITLE
JSReplacement redundancies

### ISSUE THREAD

**Issue by TriEdgeAI** [sq/JSIL#668]
Not sure if this is an issue, but here goes:

Example C# Code:

	[JSReplacement("$a * $a + $b")]
	void DoStuff(int a, int b) { ... }
	
	DoStuff(x + x, y);

Will get translated to:

	(x + x) * (x + x) + y;

While this seems a better translation:

	var _arg0 = x + x;
	_arg0 * arg0 + y;

Maybe you could introduce an optional boolean in JSReplacement which would determine whether such redundancies should be dealt with or not?

**Comment by kg** [comment]
JSReplacement intentionally just injects your arguments into the text string. I don't think this is a feature I'd add.

I could potentially expose the temporary variable mechanism I already have, and let you do something like:
```csharp
[JSReplacement("""
$temp0 = $a,
$temp1 = $b,
($temp0 * $temp0) + $b
""")]
```

**Comment by TriEdgeAI** [comment]
Yes.

**Comment by kg** [comment]
FYI: This doesn't actually matter much. Modern JS runtimes do subexpression elimination.

If the expression has side effects, however, you're right not to want to evaluate it multiple times. I don't recommend using JSReplacement in scenarios where you use a variable multiple times like that. It's best to use them a single time (as arguments to a JS function), where the JS function does the actual work. That's what I do.
