### ISSUE TITLE
List<T>.Reverse() doesn't work.

### ISSUE THREAD

**Issue by dbh1997** [sq/JSIL#672]
var list = new List<int> { 0, 1, 2, 3, 4, 5 };
            list.Reverse();
            foreach(var member in list)
            {
                Console.WriteLine(member);
            }

writes the values out in the same order instead of reverse.

**Comment by dbh1997** [comment]
Might be similar to issue with Sort not allowing ranges.

Reverse now works, Reverse range doesn’t.  I think we only use this in one spot, easy enough to work around though.

            var list = new List<int> { 0, 1, 2, 3, 4, 5 };
            list.Reverse(0, 5);
            foreach (var member in list)
            {
                Console.WriteLine(member);
            }

Thanks.

**Comment by kg** [comment]
What's your application like? Compiling mscorlib might solve most of your bcl bugs.

On February 13, 2015 8:00:45 AM PST, dbh1997 <notifications@github.com> wrote:
>Might be similar to issue with Sort not allowing ranges.
>
>Reverse now works, Reverse range doesn’t.  I think we only use this in
>one spot, easy enough to work around though.
>
>            var list = new List<int> { 0, 1, 2, 3, 4, 5 };
>            list.Reverse(0, 5);
>            foreach (var member in list)
>            {
>                Console.WriteLine(member);
>            }
>
>Thanks.
>
>From: K. Gadd [mailto:notifications@github.com]
>Sent: Friday, February 13, 2015 6:25 AM
>To: sq/JSIL
>Cc: Harris, Dave
>Subject: Re: [JSIL] List<T>.Reverse() doesn't work. (#672)
>
>
>Closed #672<https://github.com/sq/JSIL/issues/672>.
>
>—
>Reply to this email directly or view it on
>GitHub<https://github.com/sq/JSIL/issues/672#event-235375943>.
>
>________________________________
>
>Xactware's opt-in mailing list allows you to receive Xactware News that
>is of interest to you. Visit my.xactware.com today to join or to update
>your email preferences!
>
>________________________________
>
>This email is intended solely for the recipient. It may contain
>privileged, proprietary or confidential information or material. If you
>are not the intended recipient, please delete this email and any
>attachments and notify the sender of the error.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sq/JSIL/issues/672#issuecomment-74276420

- kg (mobile)
