### ISSUE TITLE
StringBuilder can't modify character at specific location with []

### ISSUE THREAD

**Issue by dbh1997** [sq/JSIL#681]
public static void Run()
        {
            StringBuilder retVal = new StringBuilder("Hello");

            Console.WriteLine(retVal[0]);
            retVal[0] = 'J';
            Console.WriteLine(retVal[0]);

            Console.WriteLine(retVal.ToString());
        }

C# output -----------------------------------

H
J
Jello

JS output --------------------------------------

H
H
Hello

**Comment by kg** [comment]
Please be aware this is a *very* slow operation with the way StringBuilder is currently implemented.
