### ISSUE TITLE
Pointer asigment with offset

### ISSUE THREAD

**Issue by iskiselev** [sq/JSIL#686]
See #677. Code that use type other than long that is written with offset by pointer is translated incorrectly.

```
using System;

public static class Program
{
    public static void Main(string[] args)
    {
    }

    private static unsafe void SHATransform(ulong* state)
    {
        var b = state[1];
        state[1] += b;
    }
}
```
Produce:
```
  function Program_SHATransform (state) {
    var b = state.getOffset(8);
    state.getOffset(8) = $T01().op_Addition(state.getOffset(8), b);
  };
```

Note: There will be no problem if we change type from UInt64 to UInt32 - probable `DecomposeMutationOperators.ConvertReadExpressionToWriteExpression` do this trick then.

**Comment by kg** [comment]
I've been thinking about making intptr 32-bit anyway since emscripten, asm.js and nacl use a 32-bit addressing model (I doubt 64-bit addresses will ever work in JS in any fashion). So this is another good reason to do that.
