### ISSUE TITLE
ReservedIdentifiers in Enum fields

### ISSUE THREAD

**Issue by iskiselev** [sq/JSIL#789]
ReservedIdentifiers in Enum fields are not escaped. Next example fails in Firefox/SpiderMonkey:
```
using System;

public enum TestMe
{
    name
}

public static class Program {
    public static void Main (string[] args) {
        Console.WriteLine(TestMe.name);
    }
}
```

**Comment by iskiselev** [comment]
ListRemoveRange test on Translated BCL fails because of this :)

**Comment by kg** [comment]
Hmm. I wonder if there are other examples of this problem.

**Comment by iskiselev** [comment]
I hope not so much - as you have ReservedIdentifiers  and change at least field names (I've not investigated it too much).
My other concerns is working of reflection if JSIL escaped member name.
