### ISSUE TITLE
Move NUnit dependency to NuGet

### ISSUE THREAD

**Issue by iskiselev** [sq/JSIL#791]
@kg, as you stated that we should move binary dependencies out of project, should we replace nUnit dll with [NUnit](http://www.nuget.org/packages/NUnit/) and [NUnitTestAdapter](http://www.nuget.org/packages/NUnitTestAdapter/)? It will also should allow everyone run test cases from VS test launcher without any plugin installation.

**Comment by kg** [comment]
Sounds like a good idea. It'd be good to see if there's a way to get vs2015 to do threaded test runs... The test suite keeps getting bigger and slower.

On August 9, 2015 10:23:22 PM PDT, Igor Kiselev <notifications@github.com> wrote:
>@kg, as you stated that we should move binary dependencies out of
>project, should we replace nUnit dll with
>[NUnit](http://www.nuget.org/packages/NUnit/) and
>[NUnitTestAdapter](http://www.nuget.org/packages/NUnitTestAdapter/)? It
>will also should allow everyone run test cases from VS test launcher
>without any plugin installation.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sq/JSIL/issues/791

- kg (mobile)
