### ISSUE TITLE
JSILc x64

### ISSUE THREAD

**Issue by iskiselev** [sq/JSIL#793]
Probably it's right time to create JSILc x64 build.
For it I suggest:
- Change Compiler project type to Class Library with Any CPU configuration
- Create 2 new project - Compiler.Executor.x86 (compile to JSILc.exe) and Compiler.Executor.x64 (compile to JSILc64.exe), that will have only one Main method, that will call current Main method from current Compiler project (now JSILc.dll).

Such configuration will allow us always build both x86 and x64 executors and it should not affect XNA compilation at all.

**Comment by kg** [comment]
Makes sense, yeah.

**Comment by iskiselev** [comment]
So can I do it?

**Comment by kg** [comment]
If you want it to happen soon, sure. I might do it myself once I have time.

Might be simpler to have Compiler\x86.csproj and Compiler\x64.csproj, so that it's obvious where to find them, alongside a Compiler\Main.csproj that builds the DLL? Something like that.
