### ISSUE TITLE
CI for JSIL

### ISSUE THREAD

**Issue by iskiselev** [sq/JSIL#794]
I think it will be good if we'll have CI.
Travis-CI provides free cloud CI for open-source projects. I was able today to build project and run Test cases [there](https://travis-ci.org/iskiselev/JSIL/builds/75019204).

Unfortunately, as they run on mono we was unable to translate mscorlib, but I hope we'll be able to run most other tests.
We still need solve problem with too big output from compile/test executions to make it more usable.

**Comment by kg** [comment]
If it's free we can definitely use it, though if it's gonna be central to the project I might want to run it myself. I have a linux box, but I'd prefer to run the CI stuff on a windows box if possible since that's where most users will be. (Having an additional CI box for linux is a good idea, though...)

**Comment by iskiselev** [comment]
I was able to run tests (on my brunch right now).
Looks like we fail a lot of tests on that box. https://travis-ci.org/iskiselev/JSIL/builds/75038382

**Comment by iskiselev** [comment]
As currently 10 tests are failing on Mono, probably I should fix CI script so that it report successful build if there is no more then 10 broken tests until we fix them?

**Comment by kg** [comment]
Is there a way to just have it report the # of passed/failed tests in the github UI? Or we can put tests known to fail on Linux into a separate category, sort of like FailingTestCases.

**Comment by iskiselev** [comment]
Excluded failing tests from CI (added to #798 PR).
As I understand, for providing additional information (number of passed tests and probably something more) we need use GitHub API from CI script. Will be good to implement :).

**Comment by iskiselev** [comment]
CI sometimes hang. Still don't know which test to blame. Probably we need split tests execution into smaller groups (edit CI config) to detect it.

**Comment by iskiselev** [comment]
I've found it - ThreadingTests.WaitThrowsIfNestedDeadlockWouldHaveOccurred is responsible for often freeze on Mono.

**Comment by iskiselev** [comment]
One more CI (free for open source) - http://www.appveyor.com/. It runs on windows, but have time limit (30 minutes) per build. So I've created config for it #828, that will build JSIL and run tests that don't work on Mono (except emscripten integration).
@kg, if you merge it and activate build there, we will have nearly full test coverage on CI.
