### ISSUE TITLE
MemberInfo doesn't implement ICustomAttributeProvider

### ISSUE THREAD

**Issue by iskiselev** [sq/JSIL#804]
Currently MemberInfo doesn't implement ICustomAttributeProvider.
When I tried to add there implementation, I found several problems:
1. MethodBase.GetParameterTypes(), MethodInfo.ReturnType, MemberInfo.Name and ParameterInfo.ParameterType was called before they were initialized in type object. This problem I was able to resolve - I've created $jsilcore.$MethodGetParameterTypes, $jsilcore.$MethodGetReturnType, $jsilcore.$MemberInfoGetName, $jsilcore.$ParameterInfoGetParameterType and call them instead (only in places that were affected).
2. JSIL.InitializeType for System.Type is called before JSIL.GetReflectionCache is finished for it.

@kg, any advise what can I do?

**Comment by iskiselev** [comment]
Please look 5739363e9f886e93c2049d18a6ee519de2c1624e as sample.
ReflectionTestCases/AttributeTypeof.cs is an example of failed tests.

**Comment by kg** [comment]
This is a (maybe unfixable?) cyclic dependency in type system initialization. JavaScript sucks.
