### ISSUE TITLE
JSIL fails on set to ref int?

### ISSUE THREAD

**Issue by iskiselev** [sq/JSIL#810]
Next test case crash JSIL on translation (if compiled with roslyn or mcs):
```
//@useroslyn

using System;

public static class Program
{
    public static void Main(string[] args)
    {
        int? a = 0;
        MoveNextCore(ref a);
        Console.WriteLine(a);
    }

    public static void MoveNextCore(ref int? currentElement)
    {
        currentElement = 100;
    }
}
```

It fails in `JSBinaryOperatorExpression.CheckInvariant` on pipeline stage `ReplaceMethodCalls`.

**Comment by kg** [comment]
Hooray for CheckInvariant! Any idea what the specific issue is? CheckInvariant should be telling you what the problem is.

**Comment by iskiselev** [comment]
I've fixed it already. Will push in minutes.
