### ISSUE TITLE
Gulp output files

### ISSUE THREAD

**Issue by kg** [sq/JSIL#818]
I keep accidentally editing the gulp outputs instead of the inputs. Can we make the outputs be set read-only (so you can't save over them) and have a one-line comment header at the top that says they're machine-generated and shouldn't be edited?

I looked through the gulp docs and couldn't see an easy way to programmatically do either of these things to all the output files.

**Comment by iskiselev** [comment]
Will look on it. For now we probably should exclude links to generated files from projects.
