### ISSUE TITLE
Right Combination of for inside switch inside for results in infinite loop in JS

### ISSUE THREAD

**Issue by dbh1997** [sq/JSIL#827]
I've spent a couple hours attempting to recreate this using simpler collections and int values but haven't been able to so far.  This is the second time I've had to refactor a function into smaller pieces to keep it from getting stuck - so there is something going on.  Not saying that refactoring isn't a good idea on large functions like this in general, but it should still work.  I have #ifdef false/#endif the C# sections of code that don't seem to have an impact.  The rest of the pieces each appear to play a role.  Whether this provides anywhere near enough to determine the problem, I don't know...  I'm optimistic that I can produce a stand alone sample given enough effort and will continue to look some more.

It gets caught in the inner while() loop that has the label $labelgroup0: above it.  Honestly, have no idea why there's a while loop at that point unless the CL compiler saw some sort of optimization opportunity in this case.  If hits both default statements which kicks it right back to the top of the loop with nothing changed.

```csharp
		public override void GetAllDimensioned(Dimensioneds dimObjs)
		{
			Dimensioneds dims = new Dimensioneds(), walls1 = new Dimensioneds();
			var levelGrpID = GetGroup().ID;

			foreach (Base pObj in Children)
			{
				if (!pObj.IsDimensionedType())
				{
					continue;
				}

                                Dimensioned pDim = (Dimensioned)pObj;
				TypeID type = pDim.SketchType;
				switch (type)
				{

					//case TypeID.ObjectBuilder:
					case TypeID.RefLine:
					case TypeID.RefPoint:
					case TypeID.ExteriorSurface:
						dims.Add(pDim);
						break;
#if false
                    case TypeID.Sector:
						{
							Sector pSector = (Sector)pDim;
							if (pSector.GetGroup().ID == levelGrpID)
							{
								dims.Add(pSector);
							}
						}
						break;
#endif
                    case TypeID.Wall:
					case TypeID.StaircaseWall://FIXIT - does this need railing wall??
					case TypeID.Fence:
						{
							Wall pWall = (Wall)pDim;
							walls1.Add(pWall); // Walls will get added into dims later...
							if (pWall.GetRoomID(0) == SysCore.SKTID_NONE)
							{
								dims.Add(pWall.GetSurface(0));
							}
							if (pWall.GetRoomID(1) == SysCore.SKTID_NONE)
							{
								dims.Add(pWall.GetSurface(1));
							}
							if (pWall.IsFenceType() || (pWall.GetRoomID(0) == 0 && pWall.GetRoomID(1) == 0)) //Level is the parent
							{
                                WallOpenings openings = pWall.GetWallOpeningChildren();
								foreach (WallOpening pOp in openings)
								{
									dims.Add(pOp);
								}
							}
							break;
						}
#if false
					case TypeID.StdRoof2: //D34220 - Add items attached to roof walls to the level.
						{
							StdRoof2 pRoof = (StdRoof2)pDim;
							RoofWalls roofWalls = new RoofWalls();
							pRoof.GetWalls(roofWalls);
							for (int wallItr = 0; wallItr < roofWalls.Count; wallItr++)
							{
								dims.Add(roofWalls[wallItr]);
							}
							Sectors sectors = new Sectors();
							pRoof.GetWallSectors(sectors);
							for (int sectItr = 0; sectItr < sectors.Count; sectItr++)
							{
								dims.Add(sectors[sectItr]);
							}
							WallOpenings wops = new WallOpenings();
							pRoof.GetWallOpenings(wops);
							for (int iInner = 0; iInner < wops.Count; iInner++)
							{
								dims.Add(wops[iInner]);
							}
						}
				        break;
#endif
				}
			}

#if false
			// Get all dimensioned children for objects in list
			Dimensioneds temp = new Dimensioneds();
			int count = dims.Count;
			for (int i = 0; i < count; i++)
			{
				var pDim = dims[i];

				// This call will include pDim in the results
                var otherDims = pDim.GetDimensionedObjs();

				// Remove pDim since it's already present in dims
				otherDims.Remove(pDim);

				temp.AddRange(otherDims);
			}
			dims.AddRange(temp);

			// Now add the walls to the list. Don't do this earlier because we don't want
			// all dimensioned children of the walls -- for instance, interior surfaces,
			// openings that don't open to level, etc. Just the WALLS, thank you.
			dims.AddRange(walls1);

			// Set the out param
			dimObjs.AddRange(dims);
#endif
		}
```

```javascript
 function Level_GetAllDimensioned (dimObjs) {
    var $temp00, $temp01;
    var dims = $S26().Construct();
    var walls = $S26().Construct();
    var arg_17_0 = ((this.GetGroup()).get_ID() | 0);

  $loop0: 
    for (var a$0 = this.get_Children()._items, i$0 = 0, l$0 = (this.get_Children()._size | 0); i$0 < l$0; ($temp00 = i$0, 
        i$0 = ((i$0 + 1) | 0), 
        $temp00)) {
      var pObj = a$0[i$0];
      if (pObj.IsDimensionedType()) {

        var $label0 = 0;
      $labelgroup0: 
        while (true) {
          switch ($label0) {
            case 0: /* $entry0 */ 
              var pDim = $T13().$Cast(pObj);
              var type = pDim.Base$SketchType$value;
              var typeID = type;
              switch (typeID.valueOf()) {
                case 5: 
                  $label0 = 1 /* goto IL_96 */ ;
                  continue $labelgroup0;

                case 6: 
                  break;

                default: 
                  switch (typeID.valueOf()) {
                    case 29: 
                    case 30: 
                      break;

                    default: 
                      switch (typeID.valueOf()) {
                        case 47: 
                        case 48: 
                          $label0 = 1 /* goto IL_96 */ ;
                          continue $labelgroup0;

                        default: 
                          continue $labelgroup0;

                      }
                      break;

                  }
                  break;

              }
              $S27().CallVirtual("Add", null, dims, pDim);
              continue $loop0;

            case 1: /* IL_96 */ 
              var pWall = $T26().$Cast(pDim);
              $S27().CallVirtual("Add", null, walls, pWall);
              if ((pWall.GetRoomID(0) | 0) === 0) {
                $S27().CallVirtual("Add", null, dims, pWall.GetSurface(0, true));
              }
              if ((pWall.GetRoomID(1) | 0) === 0) {
                $S27().CallVirtual("Add", null, dims, pWall.GetSurface(1, true));
              }
              if (!(!pWall.IsFenceType() && (((pWall.GetRoomID(0) | 0) !== 0) || 
                    ((pWall.GetRoomID(1) | 0) !== 0)))) {
                var openings = pWall.GetWallOpeningChildren();

                for (var a$1 = openings._items, i$1 = 0, l$1 = (openings._size | 0); i$1 < l$1; ($temp01 = i$1, 
                    i$1 = ((i$1 + 1) | 0), 
                    $temp01)) {
                  var pOp = a$1[i$1];
                  $S27().CallVirtual("Add", null, dims, pOp);
                }
              }

              break $labelgroup0;
          }
        }
      }
    }
  };
```

**Comment by kg** [comment]
```$labelgroupN: while (true) { switch (...) {``` is what unconstrained goto looks like in JS. It's a mess.

I think many of these bugs can only be fixed by replacing ILSpy. 

A smaller repro isn't necessary as long as I can run it. But that looks hard here... I'll look at the output later and see if I can figure out what went wrong.

**Comment by kg** [comment]
Wow, the way ILSpy decompiled this switch statement is a disaster.

```javascript
                        default: 
                          continue $labelgroup0;
```

Seems like a likely candidate for the infinite loop. That might be a bug introduced by JSIL's machinery but there's no way the function should decompile into this...

Is it possible for you to open this application with the latest standalone version of ILSpy and see what this function decompiles to (as C#) and paste it here? Thanks.

**Comment by dbh1997** [comment]
I will give that a try.  I’m guessing offhand that the way the values fall in the switch statement, that it’s perhaps grouped them into clusters and formed inner switches…

**Comment by dbh1997** [comment]
Here it is.  It indeed stuck a switch inside the default of the first switch.

public override void GetAllDimensioned(Dimensioneds dimObjs)
{
    Dimensioneds dims = new Dimensioneds();
    Dimensioneds walls = new Dimensioneds();
    int arg_17_0 = this.GetGroup().ID;
    foreach (Base pObj in base.Children)
    {
        if (pObj.IsDimensionedType())
        {
            Dimensioned pDim = (Dimensioned)pObj;
            TypeID type = pDim.SketchType;
            TypeID typeID = type;
            switch (typeID)
            {
            case TypeID.Wall:
                goto IL_96;
            case TypeID.ExteriorSurface:
                break;
            default:
                switch (typeID)
                {
                case TypeID.RefPoint:
                case TypeID.RefLine:
                    break;
                default:
                    switch (typeID)
                    {
                    case TypeID.StaircaseWall:
                    case TypeID.Fence:
                        goto IL_96;
                    default:
                        continue;
                    }
                    break;
                }
                break;
            }
            dims.Add(pDim);
            continue;
            IL_96:
            Wall pWall = (Wall)pDim;
            walls.Add(pWall);
            if (pWall.GetRoomID(0) == 0)
            {
                dims.Add(pWall.GetSurface(0, true));
            }
            if (pWall.GetRoomID(1) == 0)
            {
                dims.Add(pWall.GetSurface(1, true));
            }
            if (pWall.IsFenceType() || (pWall.GetRoomID(0) == 0 && pWall.GetRoomID(1) == 0))
            {
                WallOpenings openings = pWall.GetWallOpeningChildren();
                foreach (WallOpening pOp in openings)
                {
                    dims.Add(pOp);
                }
            }
        }
    }
}

**Comment by kg** [comment]
OK, I think what's happening is that the unlabelled continue is getting mistranslated. I can probably fix that. Thanks.

**Comment by dbh1997** [comment]
I couldn’t compel the compiler to create the exact same layout, but this one does generate a switch in a switch with a default with a continue statement – and locks up just as well.

        public static void Test()
        {
            var list = new List<int>();
            list.Add(10);
            list.Add(5);
            foreach (var mem in list)
            {
                switch (mem)
                {
                    case 29:
                    case 30:
                    case 6:
                    {
                        Console.WriteLine("A");
                        break;
                    }
                    case 5:
                    case 47:
                    case 48:
                    {
                        Console.WriteLine("B");
                        break;
                    }
                    case 70:
                    {
                        Console.WriteLine("C");
                        break;
                    }
                }
            }
        }


public static void Test()
{
    foreach (int mem in new List<int>
    {
        10,
        5
    })
    {
        int num = mem;
        if (num <= 30)
        {
            switch (num)
            {
            case 5:
                goto IL_7B;
            case 6:
                break;
            default:
                switch (num)
                {
                case 29:
                case 30:
                    break;
                default:
                    continue;
                }
                break;
            }
            Console.WriteLine("A");
        }
        else
        {
            switch (num)
            {
            case 47:
            case 48:
                goto IL_7B;
            default:
                if (num == 70)
                {
                    Console.WriteLine("C");
                }
                break;
            }
        }
        continue;
        IL_7B:
        Console.WriteLine("B");
    }
}

**Comment by kg** [comment]
Thanks for the straightforward test case. Later on I might want to find a way to undo the crazy control flow ILSpy generates here, but at least it works now...
