### ISSUE TITLE
String created through ctor behaves incorrectly

### ISSUE THREAD

**Issue by iskiselev** [sq/JSIL#845]
When translted code creates string using any constructor, JS String object created (instead of primitive). All type checks do not count String object as System.String.
I'm pretty sure that we should treat it as System.String also.
Here is test case:
```
using System;

public static class Program {
    public static void Main ()
    {
        var str = GetString();
        Console.WriteLine(str.GetType().Name);
        Console.WriteLine(str is string ? "true" : "false");
    }

    public static object GetString()
    {
        return new string('a', 10);
    }
}
```

For fixing it we should change:
- In System.Sting.js
```
    $.RawMethod(true, "CheckType",
      function (value) {
        return (typeof (value) === "string" || value instanceof String);
      }
    );
```
- In JSIL.GetType
```
...
  if ((type === "object") || (type === "function")) {
    var tt;
    if (tt = value.__ThisType__)
      return tt;
    else if (value.GetType)
      return value.GetType();
    else if (value instanceof String )
      return System.String.__Type__;
    else if (JSIL.IsTypedArray(value))
      return JSIL.$GetTypeForTypedArray(value);
    else if (JSIL.IsArray(value))
      return System.Array.__Type__;
    else
      return System.Object.__Type__;

  } else if (type === "string" ) {
    return System.String.__Type__;
  }
...
```

Probably we should do the same for Number object. I'm not sure if we need change string constructor to return sting primitive.

**Comment by kg** [comment]
JSIL should never create String or Number instances. This used to work right. :/ JavaScript's approach to strings is absurd.

**Comment by iskiselev** [comment]
In that case we should fix Sting constructors. They currently create new String(...) inside - so they creates sting object.
On other side - do we really want treat sting object created in outer JS code as System,Object versus treating it as .Net System.String?

**Comment by kg** [comment]
> On other side - do we really want treat sting object created in outer JS code as System,Object versus treating it as .Net System.String?

I don't understand this question, sorry.

**Comment by iskiselev** [comment]
If some code (that works in pair of JSIL translate app) will create string object (using something like `new Sting("some string")` and will pass this string object to any ,Net translated method, and translated method will try resolve type of such object - what should it see - System.Object or System.String?
Or, a little bit  easier, what should return next example when translated:
```
using System;
using JSIL;

public static class Program {
    public static void Main ()
    {
        Console.WriteLine(GetString().GetType().Name);
        Console.WriteLine(GetString() is string ? "true" : "false");
    }

    public static object GetString()
    {
        return Verbatim.Expression("new String(\"test\")") ?? "test";
    }
}
```

**Comment by kg** [comment]
GetType of js strings should be System.String, yes. That used to work also. I'm surprised tests didn't cover this

**Comment by iskiselev** [comment]
The problem here is that Sting/Number in JS can be in two forms - primitive or object. Here is example:
```
function TestIfString(obj) {
   console.log(typeof(obj) === "string");
   console.log(obj instanceof String);
}
TestIfString("test") 
//Output: true false
TestIfString(new String("test"))
//Output: false true
```

JSIL correctly detects Type in first case - if sting created as primitive, but will not work in second - when Sting created as String object (but, of course will works correctly if you will check `new String("aaa".valueOf()`).

That's why I suggested change in type detection logic. We still may need change System.String .net constructors implementation so that they returns primitive JS type.

**Comment by iskiselev** [comment]
I'm looking on this issue right now and want to do a proper fix.
When we call ctor on string, call pass through next auto-generated function:
```
(function(typeObject,publicInterface,constructor
/**/) {
"use strict";
function ConstructorSignature_Construct$2(arg0, arg1) {
      return new constructor(
        arg0,
        arg1
      );
    };
        return ConstructorSignature_Construct$2;

})
```

This method is generated by `JSIL.ConstructorSignature.prototype.$MakeConstructMethod`. It looks for me, that auto-generated method will be shared for all same ConstructorSignature (even in different type). Does it?
If yes, then why it works different if `typeObject.__IsNativeType__`? See:
```
  if (typeObject.__IsNativeType__) {
    closure.ctor = publicInterface.prototype["_ctor"];

    JSIL.MethodSignature.$EmitInvocation(
      body, "ctor.call", "publicInterface", 
      "return ", argumentTypes
    );
  } else {
    closure.constructor = this.$MakeBoundConstructor(
      argumentNames
    );
    
    JSIL.MethodSignature.$EmitInvocation(
      body, "new constructor", null, 
      "return ", argumentTypes
    );

    if (typeObject.FullName === "System.String") {
      body += ".valueOf()";
    }
  }
```

If it is not shared, then it will be safe generate special form here for String case (same as already done with `__IsNativeType__`)

**Comment by kg** [comment]
The mistake here is probably that String isn't marked as a native type and should be.

The constructor function looks shared but isn't; it closes over 'constructor' and 'typeObject' so you need a new instance for every type. It just potentially shares a function body.

**Comment by kg** [comment]
I may have misread your messages so to clarify: It is safe to generate a special form for String just like with the other native types.

**Comment by iskiselev** [comment]
Good, thank you for clarification! I already tried to set `__IsNativeType__` for string, but it don't work with only that change. I ended in next function:
```
(function(name,offset
/**/) {
"use strict";
function System_String__ctor(arg0, arg1, arg2) {
      var argc = arguments.length | 0;
    switch (argc) {
      case 1:
            return this.$$9b(arg0);
        break;
      case 2:
            return this.$$9c(arg0, arg1);
        break;
      case 3:
            return this.$$9d(arg0, arg1, arg2);
        break;
      default:
          JSIL.RuntimeError('No overload of ' + name + ' can accept ' + (argc - offset) + ' argument(s).')
        break;
    }
    };
        return System_String__ctor;

})
```

this object was `<System.String Public Interface>`, but there was no $$9b/$$9c/$$9d defined on it.

**Comment by kg** [comment]
That is probably because the built-in types are excluded from a bunch of the JSIL infrastructure - it's probably not actually producing all the type info for String or initializing all the methods.
