### ISSUE TITLE
Interface implementations for raw types

### ISSUE THREAD

**Issue by iskiselev** [sq/JSIL#865]
This issue relates to #846, #787, #241, #864.
We should decide, how we will provide interface method implementations for raw JS types objects.
If I'm correct, here is full list of such objects:
1. Numbers: Byte, SByte, Int16, UInt16, Int32, UInt32
2. Boolean
3. Char
4. String
5. Array

Here is full list of interface that they implement:
1. (All except array) IComparable, IConvertible, IComparable<T>, IEquatable<T>
2. (Numbers) IFormattable
3. (String and arrays) ICloneable, IEnumerable, IEnumerable<char>
4. (Arrays) IList, ICollection, IStructuralComparable, IStructuralEquatable, IList<T>, ICollection<T>, IReadOnlyList<T>, IReadOnlyCollection<T>

I see several approaches for it:
1. Use JSIL.Box<T> for calling interface methods as proposed in #864. This solve problem for structs, but we still have problem with arrays and strings. We may introduce something similiar for them (as already done with JSIL.ArrayInterfaceOverlay), but it introduce reference equals problem - see #787.
2. Apply JSReplace attribute to all members of interfaces, that will use some static helper with passing this as first argument. May need additional tweaks for calls through delegate/reflection (see #850 as example).
3. Attach required methods to Array/String prototype - looks like a dirty hack for me.

@kg, could you suggest some additional options? What is you opinion? It looks for me that (2)
 option is best.

**Comment by kg** [comment]
Boxes should implement interfaces. For arrays and strings we should use interface overlays. Note that reference equality is already broken for strings, as JS has no concept of reference equality for any type other than Object.

**Comment by kg** [comment]
Oh, on second thought: Since interface calls can be done indirectly via the ```IInterface.MethodName``` property they expose maybe we can just modify things so those 'special' system interfaces always go through an invocation path that will work on those built-in types. Then we can make them work on arrays and strings through a fallback path (```if (typeof (x) !== 'object') fallback```)

**Comment by iskiselev** [comment]
What is incorrect with reference equals in JavaScript? It works for any object created with new.
All primitive type with same value will also be Equals. So, reference equals now will work with strings created in object form through constructor.

**Comment by kg** [comment]
Using the ```String``` object is almost never appropriate. The typeof is wrong and doing addition on it will produce a ```string``` instead of a ```String```. If we mix the two types a bunch of stuff will break. If we use ```String``` various third-party JS (and DOM APIs) may not work correctly. I'm pretty sure ```String``` is slower, too, and it may disable certain engine optimizations like ropes.

**Comment by iskiselev** [comment]
Really, right now, JSIL use String object if string is created through ctor, otherwise it use string-value.
It may be even good, as in .Net, most strings pass through `string.Intern`, which returns same instance of string per app. Probably we should implement it as string.valueOf.

**Comment by kg** [comment]
Yeah, using the ```String``` constructor is wrong, not sure why it's doing that. Thanks for pointing it out.
I do think most code won't depend on string referential equality, and probably shouldn't. So we're pretty lucky there.

**Comment by iskiselev** [comment]
In any case, it is probably OK if two different string instance with same content are equals by reference (current _a little bit_ broken behaviour). Using interface overlays will broke it in worth way  - two same string may be not equal by reference.

So I'll look on your suggestion force special interface method caller for that types and fix it inside, but I really don't like interface overlay idea.

**Comment by kg** [comment]
Yeah, I think the interface method call thing is a better idea in general. It might eliminate the need for array interface overlays too.

**Comment by iskiselev** [comment]
Right now there is next comment:
```
// FIXME: This can probably be replaced with compiler and/or runtime intelltypeigence 
//  to create interface overlays for strings, just like arrays.
JSIL.$PickFallbackMethodForInterfaceMethod = function (interfaceObject, methodName, signature) {
```

But looks like we still not found any better options?
