### ISSUE TITLE
EliminateTemporaries works incorrectly

### ISSUE THREAD

**Issue by iskiselev** [sq/JSIL#868]
I'm looking on very strange issue now. I have a problem when translate `Stack<T>.Pop`.
Looks like this issue was recently introduce (tomorrow will check, if it is only my version problem, but should not be). I suspect it was introduced when backends were merged.

This issue is not reproduced in isolated test case, but is reproducible in translated BCL test cases.

Original method:
```
    public T Pop()
    {
      if (this._size == 0)
        ThrowHelper.ThrowInvalidOperationException(ExceptionResource.InvalidOperation_EmptyStack);
      this._version = this._version + 1;
      T[] objArray = this._array;
      int num = this._size - 1;
      this._size = num;
      int index = num;
      T obj = objArray[index];
      this._array[this._size] = default (T);
      return obj;
    }
```

After translation:
```
  function Stack$b1_Pop () {
    if ((this._size | 0) === 0) {
      $T01().ThrowInvalidOperationException($T03().InvalidOperation_EmptyStack);
    }
    this._version = (((this._version | 0) + 1) | 0);
    var arg_34_0 = this._array;
    var num = (((this._size | 0) - 1) | 0);
    this._size = num;
    this._array[this._size] = (
      $thisType.T.get(this).IsValueType
         ? JSIL.CreateInstanceOfType($thisType.T.get(this))
         : null)
    ;
    return arg_34_0[num];
  }; 
```

So, it skipped saving `arg_34_0[num]` as temporary variable. This transformation was done on `EliminateTemporaries` pipeline step.

**Comment by iskiselev** [comment]
Commit b663720bee7b90df0da7c0967c70ba903ce834ec introduced this issue.
Test case (from SimpleTestCasesForTranslatedBcl folder):
```
using System;
using System.Collections.Generic;

public static class Program
{
    public static void Main(string[] args)
    {
        var stack = new Stack<string>();
        stack.Push("test");
        Console.WriteLine(stack.Pop());
    }
}
```

**Comment by kg** [comment]
Wow, weird. There's no field access there.

**Comment by iskiselev** [comment]
@kg, this looks suspicious for me (inside IsEffectivelyConstant):
```
            {
                var ie = source as JSIndexerExpression;
                if (ie != null) {
                    if (
                        IsEffectivelyConstant(target, ie.Target) &&
                        IsEffectivelyConstant(target, ie.Index)
                    )
                        return true;
                }
            }
```
Here is a check for `indexed[index]`, which validate that both `indexed` and `index` are constants, but skip that whole expression is not necessary constant. So, probably that commit just help us found another issue.

**Comment by kg** [comment]
OK, that makes sense. That code is probably broken because the effectively-constant status does not properly examine reference types. I think it shouldn't work that way for fields either, so I screwed up.

**Comment by iskiselev** [comment]
Checked more - that sample is not responsible for problem, but still looks suspicious.
With field.IsImmutable check it changed that in `T[] objArray = this._array;` objArray don't treat as constant anymore. Why it broke `T obj = objArray[index];` I still don't know.

**Comment by iskiselev** [comment]
Got it! (My previous comment was incorrect)
With your change `T[] objArray` is constant now, so indexer expression is also treat as constant and eliminated.
Probably we need fully exclude this special case for JSIndexerExpression or introduce some much more complex logic (this will be valid with some additional checks for array indexer, but will be invalid in general case with indexed properties).

**Comment by kg** [comment]
Yeah, it's probably incorrect for the array to be constant. Arrays are never immutable in .NET.
