### ISSUE TITLE
Decimal values should be created through constructor

### ISSUE THREAD

**Issue by iskiselev** [sq/JSIL#871]
JSIL use special type for handling decimal values (separate from Number), but still use raw Number if decimal created through `JSNumberLiteral`.
We should fix it. @kg which option do you prefer:
1. Replace JSNumberLiteral<decimal> with constructor call as step of pipeline (I suppose something similar happens with int64?)
2. Create JSDecimalLiteral and return it from JSLiteral.New(decimal) with special method in JavascriptAstEmitter.
3. Just write special logic inside JavascriptAstEmitter.VisitNode (JSNumberLiteral number).

**Comment by kg** [comment]
JSDecimalLiteral sounds best.
