### ISSUE TITLE
Static method delegates with a 'this' parameter fails to run

### ISSUE THREAD

**Issue by callanh** [sq/JSIL#875]
The following code fragment doesn't work correctly when converted to JS.  The call to TestAction passes "Hello World" as the Self variable, Value is undefined and of course the JS runtime throws an exception.

This is the minimal code to reproduce the issue:

  static class WebProgram
  {
    static void Main(string[] args)
    {
      var Data = new Data();
      Action<string> TestAction = Data.SetValue;
      TestAction("Hello World");
    }
  }

  public sealed class Data
  {
    public string Name { get; set; }
  }

  public static class Helper
  {
    public static void SetValue(this Data Self, string Value)
    {
      Self.Name = Value;
    }
  }

**Comment by iskiselev** [comment]
Fixed test case:
```
using System;

public static class Program
{
    public static void Main(string[] args)
    {
        var Data = new Data();
        Action<string> TestAction = Data.SetValue;
        TestAction("Hello World");
        Console.WriteLine(Data.Name);
    }
}

public sealed class Data
{
    public string Name { get; set; }
}

public static class Helper
{
    public static void SetValue(this Data Self, string Value)
    {
        Self.Name = Value;
    }
}
```

Key point here is that SetValue is an extension method. Will look more on it later.

**Comment by iskiselev** [comment]
Let' look on it a little bit more:
```
using System;
using System.Collections.Generic;

public static class Program
{
    public static void Main(string[] args)
    {
        var Data = new Data();
        Action<string> TestAction = Data.SetValue2;
        TestAction("Hello World");
        Action<string> TestAction2 = Data.SetValue;
        TestAction2("Hello World");
    }
}

public sealed class Data
{
    public string Name { get; set; }
    public void SetValue2(string Value)
    {
        this.Name = Value;
    }
}

public static class Helper
{
    public static void SetValue(this Data Self, string Value)
    {
        Self.Name = Value;
    }
}
```

So, now we have SetValue2 as instance method and SetValue as extension. Let's look on translation:
```
    var TestAction = $T02().New(Data, function () { return $T01().prototype.SetValue2.call(Data, arguments[0]); }.bind(this), function () { return JSIL.GetMethodInfo($asm00.Data, "SetValue2", $S00(), false); }.bind(this));
    var TestAction2 = $T02().New($T03(), function () { return $T03().SetValue(arguments[0], arguments[1]); }.bind(this), function () { return JSIL.GetMethodInfo($asm00.Helper, "SetValue", $S01(), true); }.bind(this));
```

Now let's look on CIL:
```
	IL_0007: ldloc.0
	IL_0008: ldftn instance void Data::SetValue2(string)
	IL_000e: newobj instance void class [mscorlib]System.Action`1<string>::.ctor(object, native int)
...
	IL_0020: ldloc.0
	IL_0021: ldftn void Helper::SetValue(class Data, string)
	IL_0027: newobj instance void class [mscorlib]System.Action`1<string>::.ctor(object, native int)
```

In .Net VM, this of method is really nothing more than first argument. So, internaly call to instance method and external method looks same. On the same principle based, that you can created delegate detached from target instance (see #624, #708).
When we keep in mind #800, looks like it is good time to think about delegate implementation once again. Right now I don't see proper solutions. Any thoughts?
