### ISSUE TITLE
Typo in JSIL.Core.js

### ISSUE THREAD

**Issue by callanh** [sq/JSIL#876]
I believe that the plus '+' below should be a comma ','.  Fails with a format string exception instead of the warning message.

JSIL.Core.js:1165

```javascript
JSIL.WarningFormat(
            "Private type '{0}' with external implementation defined more than twice: '{1}'" + 
            [$private.toString(), existing.toString()]
```

**Comment by kg** [comment]
You're right. Thanks.

**Comment by iskiselev** [comment]
Sorry, please reopen this and close #875 instead. Looks like I've there was typo in commit message.
