### ISSUE TITLE
Foreach closures and variable locality with anonymous delegates

### ISSUE THREAD

**Issue by callanh** [sq/JSIL#880]
I may have found a significant bug!  An important pattern (to me at least) is declaring anonymous delegates inside a foreach.  The real use case is for dynamic UI generation.  Imagine the reproduction case below is foreach creating buttons with the click event handled.

```C#
using System;

static class Program
{
  static void Main(string[] args)
  {
    var List = new List<Action>();

    foreach (var Index in new int[] { 1, 2, 3 })
    {
      var Local = Index;

      List.Add(() => Console.WriteLine("Delegate Index(" + Index + ") vs Local(" + Local + ")"));
    }

    foreach (var Action in List)
      Action();
  }
}
```

In this example, it will print to the console:

```
Delegate Index(3) vs Local(3)
Delegate Index(3) vs Local(3)
Delegate Index(3) vs Local(3)
```

When it needs to print:

```
Delegate Index(1) vs Local(1)
Delegate Index(2) vs Local(2)
Delegate Index(3) vs Local(3)
```

Interestingly, JSIL is giving the same behaviour as once defined in the C# standard. You may remember that Microsoft retrospectively changed the implementation in the C# 5.0 Standard.

**Comment by kg** [comment]
That's interesting. I wonder if this is ILSpy decompiling into a foreach and me implementing the old semantics.

**Comment by kg** [comment]
When I run that snippet on ```try.jsil.org``` it produces the desired output. Any ideas? Maybe mono's C# compiler is producing something that decompiles correctly?

If you can send me a .dll or .exe that contains your compiled version of this test case, that would help me make sure I can reproduce it here. (I will be trying it out locally at some point)

**Comment by callanh** [comment]
I've sent you via email because it won't let me post an .exe file.

**Comment by iskiselev** [comment]
Looks like I've broken this through PR #807.

**Comment by callanh** [comment]
Out of interest, the pre C# 5.0 Standard behaviour would actually have been:

```
Delegate Index(3) vs Local(1)
Delegate Index(3) vs Local(2)
Delegate Index(3) vs Local(3)
```

Note that the Local variable was a workaround for the foreach variable not being scoped in a useful way.

**Comment by iskiselev** [comment]
There is nothing with C# standard. Problem is inside calling of delegate inside JSIL after my last fix. Hope to find solution and fix it soon.

**Comment by iskiselev** [comment]
Issue could be closed.
