### ISSUE TITLE
Play mp3 sfx from byte array

### ISSUE THREAD

**Issue by callanh** [sq/JSIL#885]
I'm trying to play an mp3 sound effect from a byte array.

Web Audio API seems promising: http://www.html5rocks.com/en/tutorials/webaudio/intro/.  I can see it is not broadly supported by the browsers, but should be working in Chrome.

I suspect my problem is how to pass a byte array to the source.buffer?

```C#
var AudioClass = window.AudioContext;
if (AudioClass != WebObject.undefined)
{
  var AudioContext = JSIL.Verbatim.Expression("new $0()", AudioClass);
  var AudioSource = AudioContext.createBufferSource();
  AudioSource.buffer = Mp3ByteArray;
  AudioSource.connect(AudioContext.destination);
  AudioSource.start(0);
}
```

Any advice or alternative solutions would be appreciated!

**Comment by kg** [comment]
If you allocate ```byte[]``` in C# you will get a ```Uint8Array``` in JS. You'll need to create an [```AudioBuffer```](https://developer.mozilla.org/en-US/docs/Web/API/AudioBuffer) and then upload samples into it.

If you have raw samples, [```copyToChannel```](https://developer.mozilla.org/en-US/docs/Web/API/AudioBuffer/copyToChannel) will do the trick. If you have an mp3 in a byte array, you'll want to use [```decodeAudioData```](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/decodeAudioData). Note that ```decodeAudioData``` is async.

The FNA port does this to implement the ```Song``` type, see here: https://github.com/sq/FNA/blob/master/src/Media/JSIL/Song.cs#L26

**Comment by callanh** [comment]
Thanks @kg, decodeAudioData was the missing piece of the puzzle.

For completeness:

```C#
internal void PlaySound(byte[] Buffer, float Volume)
{
  var AudioClass = window.AudioContext;
  if (AudioClass != WebObject.undefined)
  {
    var AudioContext = JSIL.Verbatim.Expression("new $0()", AudioClass);

    dynamic AudioBufferDynamic = Buffer;
    object AudioBufferObject = AudioBufferDynamic.buffer;
    Action<object, float> AudioDecodeComplete = AudioDecodePlay;

    AudioContext.decodeAudioData(AudioBufferObject, JSIL.Verbatim.Expression("function (buffer) { $0(buffer, $1); }", AudioDecodeComplete, Volume));
  }
}

private void AudioDecodePlay(object AudioBuffer, float Volume)
{
  var AudioSource = AudioContext.createBufferSource();
  AudioSource.buffer = AudioBuffer;
  AudioSource.connect(AudioContext.destination);

  if (Volume != 1.0F)
  {
    var AudioVolume = AudioContext.createGain();
    AudioSource.connect(AudioVolume);
    AudioVolume.connect(AudioContext.destination);
    AudioVolume.gain.value = Volume;
  }

  AudioSource.start(0);
}

```

I've also implemented a dictionary to cache the AudioBuffer objects to save the decode step for the same sound effect.

**Comment by kg** [comment]
You should make sure to retain your AudioContext instance and reuse it.
