### ISSUE TITLE
having trouble building solution with JSIL

### ISSUE THREAD

**Issue by 0xFireball** [sq/JSIL#945]
C:\Program Files (x86)\MSBuild\Microsoft\XNA Game Studio\v4.0\Microsoft.Xna.GameStudio.ContentPipeline.targets(78,5): error MSB4062: The "BuildContent" task could not be loaded from the assembly Microsoft.Xna.Framework.Content.Pipeline, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842cf8be1de50553. Could not load file or assembly 'Microsoft.Xna.Framework.Content.Pipeline, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842cf8be1de50553' or one of its dependencies. The system cannot find the file specified. Confirm that the declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

when running JSILc.exe

BUT, it builds in a Developer command prompt and VS2015 Community jsut fine

**Comment by kg** [comment]
Are you running JSILc from a developer command prompt? That might be necessary.

**Comment by 0xFireball** [comment]
exact same error

**Comment by 0xFireball** [comment]
Project "C:\Users\0xFireball\Documents\GitHub\Thunderhead---The-Original-Game\Thunderhead 4.4\Thunderhead\Thunderhead.csproj" is building "C:\Users\0xFireball\Documents\GitHub\Thunderhead---The-Original-Game\Thunderhead 4.4\ThunderheadContent\ThunderheadContent.contentproj" (default targets):

C:\Program Files (x86)\MSBuild\Microsoft\XNA Game Studio\v4.0\Microsoft.Xna.GameStudio.ContentPipeline.targets(78,5): error MSB4062: The "BuildContent" task could not be loaded from the assembly Microsoft.Xna.Framework.Content.Pipeline, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842cf8be1de50553. Could not load file or assembly 'Microsoft.Xna.Framework.Content.Pipeline, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842cf8be1de50553' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
Done building project "ThunderheadContent.contentproj" -- FAILED.
// Compilation failed for target 'Build': Unknown error
// Out-of-process solution build completed successfully.
// Auto-selected the profile 'XNA4' for this project.
// Processing content project 'C:\Users\0xFireball\Documents\GitHub\Thunderhead---The-Original-Game\Thunderhead 4.4\ThunderheadContent\ThunderheadContent.contentproj' ...
menuscreen.png
playbutton.png
newbutton.png
System.IO.FileNotFoundException: Asset thunderhead_font_01.spritefont was not built.
   at Common.CopyXNB(Action`3 logOutput, String type, String localOutputDirectory, String xnbPath, ProjectItem item) in C:\FileLab\JSIL\Compiler\Profiles\XNACommon.cs:line 1112
   at Common.<>c__DisplayClass28_0.<ProcessContentProjects>b__7(ProjectItem item, String xnbPath, String type) in C:\FileLab\JSIL\Compiler\Profiles\XNACommon.cs:line 885
   at Common.ProcessContentProjects(VariableSet variables, Configuration configuration, BuildResult buildResult, HashSet`1 contentProjectsProcessed) in C:\FileLab\JSIL\Compiler\Profiles\XNACommon.cs:line 986
   at JSIL.Compiler.Profiles.XNA4.ProcessBuildResult(VariableSet variables, Configuration configuration, BuildResult buildResult) in C:\FileLab\JSIL\Compiler\Profiles\XNA4\XNA4Profile.cs:line 56
   at JSIL.Compiler.Program.ParseCommandLine(IEnumerable`1 arguments, List`1 buildGroups, Dictionary`2 profiles, Dictionary`2 analyzers, Dictionary`2 emitterFactories, AssemblyCache assemblyCache) in C:\FileLab\JSIL\Compiler\Program.cs:line 447
   at JSIL.Compiler.Program.InternalMain(String[] arguments) in C:\FileLab\JSIL\Compiler\Program.cs:line 714
   at JSIL.Compiler.Program.Main(String[] arguments) in C:\FileLab\JSIL\Compiler\Program.cs:line 695

**Comment by kg** [comment]
Hm, not sure what to do about that. If I find some time I'll try to figure out why this would be happening... XNA and MSBuild are largely outside my control.

**Comment by 0xFireball** [comment]
is there a workaround?
i can successfully build the .exe but this error comes when building the solution

**Comment by 0xFireball** [comment]
the main problem i am trying to solve is that i am unable to build a manifest for my contentproj.
You said that i could do this by building the sln in JSILc, but as i said, this isn't working. When i build the exe, i dont get the contentproj manifest.

how can i get this without building the sln, which isn't working?

**Comment by kg** [comment]
You could create a content manifest by hand, but you'd also have to convert all your assets to web formats. It sounds like something changed about either msbuild or XNA since the last time I tested everything.

**Comment by 0xFireball** [comment]
ouch.
ok

**Comment by 0xFireball** [comment]
but looking closely, the main error is that 
Microsoft.Xna.Framework.Content.Pipeline
is not found!
i installed the MXA game studio

**Comment by 0xFireball** [comment]
wait actually the buildcontent task insidie it ?
but the file is in my GAC

**Comment by 0xFireball** [comment]
does this work fine otherwise?

**Comment by 0xFireball** [comment]
how do i create a content manifest?

**Comment by dmirmilshteyn** [comment]
@0xFireball I wrote a small command line application as part of my build process which generates a content manifest for all files in a given directory without needing JSILc to directly compile your solution. It doesn't do anything special for XNA files (I haven't really taken a look at how XNA support works here), but I guess it would be a starting point for you. Will that help you?

**Comment by 0xFireball** [comment]
i hope so! can i see it?

**Comment by dmirmilshteyn** [comment]
Sure. Give me a few days to rip it out of my build system. I'll post the link here when I'm done.

**Comment by 0xFireball** [comment]
sure. thanks!

**Comment by iskiselev** [comment]
@0xFireball, please check that you've run JSILc.exe and not JSILc.AnyCPU.exe.

**Comment by 0xFireball** [comment]
I have tried running JSILc.exe and JSILc.AnyCPU.exe. Both give an identical failure result. If it helps, I have verified this on 3 independent 64-bit Windows 10 machines, and two of them are clean installs with only Visual Studio and XNA.

**Comment by 0xFireball** [comment]
Here is the entire output:


// Applied settings from 'C:\FileLab\jsilbin\defaults.jsilconfig'.
// Starting out-of-process solution build with ID 'JSIL.Build268188F1'...
// Running target 'Build' of 'Thunderhead 4.4\Thunderhead.sln' ...
// Generating MSBuild projects for solution 'Thunderhead.sln'... 1 project(s) generated.
// Building project 'C:\Users\0xFireball\Documents\GitHub\Thunderhead---The-Original-Game\Thunderhead 4.4\Thunderhead.sln.metaproj'...
__________________________________________________
Project "C:\Users\0xFireball\Documents\GitHub\Thunderhead---The-Original-Game\Thunderhead 4.4\Thunderhead.sln.metaproj" (Build target(s)):

__________________________________________________
Project "C:\Users\0xFireball\Documents\GitHub\Thunderhead---The-Original-Game\Thunderhead 4.4\Thunderhead.sln.metaproj" is building "C:\Users\0xFireball\Documents\GitHub\Thunderhead---The-Original-Game\Thunderhead 4.4\Thunderhead\Thunderhead.csproj" (default targets):

__________________________________________________
Project "C:\Users\0xFireball\Documents\GitHub\Thunderhead---The-Original-Game\Thunderhead 4.4\Thunderhead\Thunderhead.csproj" is building "C:\Users\0xFireball\Documents\GitHub\Thunderhead---The-Original-Game\Thunderhead 4.4\ThunderheadContent\ThunderheadContent.contentproj" (default targets):

C:\Program Files (x86)\MSBuild\Microsoft\XNA Game Studio\v4.0\Microsoft.Xna.GameStudio.ContentPipeline.targets(78,5): error MSB4062: The "BuildContent" task could not be loaded from the assembly Microsoft.Xna.Framework.Content.Pipeline, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842cf8be1de50553. Could not load file or assembly 'Microsoft.Xna.Framework.Content.Pipeline, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842cf8be1de50553' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
Done building project "ThunderheadContent.contentproj" -- FAILED.
// Compilation failed for target 'Build': Unknown error
// Out-of-process solution build completed successfully.
// Auto-selected the profile 'XNA4' for this project.
// Processing content project 'C:\Users\0xFireball\Documents\GitHub\Thunderhead---The-Original-Game\Thunderhead 4.4\ThunderheadContent\ThunderheadContent.contentproj' ...
menuscreen.png
playbutton.png
newbutton.png
System.IO.FileNotFoundException: Asset thunderhead_font_01.spritefont was not built.
   at Common.CopyXNB(Action`3 logOutput, String type, String localOutputDirectory, String xnbPath, ProjectItem item) in C:\FileLab\JSIL\Compiler\Profiles\XNACommon.cs:line 1112
   at Common.<>c__DisplayClass28_0.<ProcessContentProjects>b__7(ProjectItem item, String xnbPath, String type) in C:\FileLab\JSIL\Compiler\Profiles\XNACommon.cs:line 885
   at Common.ProcessContentProjects(VariableSet variables, Configuration configuration, BuildResult buildResult, HashSet`1 contentProjectsProcessed) in C:\FileLab\JSIL\Compiler\Profiles\XNACommon.cs:line 986
   at JSIL.Compiler.Profiles.XNA4.ProcessBuildResult(VariableSet variables, Configuration configuration, BuildResult buildResult) in C:\FileLab\JSIL\Compiler\Profiles\XNA4\XNA4Profile.cs:line 56
   at JSIL.Compiler.Program.ParseCommandLine(IEnumerable`1 arguments, List`1 buildGroups, Dictionary`2 profiles, Dictionary`2 analyzers, Dictionary`2 emitterFactories, AssemblyCache assemblyCache) in C:\FileLab\JSIL\Compiler\Program.cs:line 447
   at JSIL.Compiler.Program.InternalMain(String[] arguments) in C:\FileLab\JSIL\Compiler\Program.cs:line 714
   at JSIL.Compiler.Program.Main(String[] arguments) in C:\FileLab\JSIL\Compiler\Program.cs:line 695

**Comment by kg** [comment]
I assume you're using VS2015 + the VS2015 compatible version of XNA, is that right?

**Comment by 0xFireball** [comment]
Yes.

**Comment by dmirmilshteyn** [comment]
This won't fix your issue, but maybe it can help you with generating the manifests externally: https://github.com/dmirmilshteyn/JSILContentManifestGenerator

**Comment by iskiselev** [comment]
You can also try to copy Microsoft.Xna.Framework.Content.Pipeline.dll and its' dependencies recursively in JSIL/bin folder (or register them in GAC).

**Comment by 0xFireball** [comment]
The DLL is already  in the GAC.

**Comment by kg** [comment]
I feel like the load failure in msbuild represents something very wrong
with assembly resolve. Can you set up some fusion logging and figure out
the exact reason the assembly load is failing?
http://www.hanselman.com/blog/BackToBasicsUsingFusionLogViewerToDebugObscureLoaderErrors.aspx
