### ISSUE TITLE
build error in VS 2015 Pro

### ISSUE THREAD

**Issue by tedf619** [sq/JSIL#946]
I don't have NUnit on my machine so I disabled the 3 NUnit projects. I also disabled the XNA projects. When I build the solution, all the enabled projects build ok except for JSIL_Libraries, which produces  the error:

------ Build started: Project: JSIL.Libraries, Configuration: Debug Any CPU ------
<b>C:\JSIL\JSIL.Libraries\Targets\MSBuild.Npm.targets(11,9): error MSB3073: The command "".bin\npm" install --loglevel error" exited with code 1.</b>

What am I missing?

**Comment by iskiselev** [comment]
Can you provide full output of JSIL.Libraries compilation?

**Comment by iskiselev** [comment]
Really, all NUnit assemblies should be installed automatically through NuGet, so even test project should work.

**Comment by tedf619** [comment]
Here is a relevant fragment of the VS2015 output during build:

10>------ Build started: Project: JSIL.Libraries, Configuration: Debug Any CPU ------
10>Build started 2016-01-19 16:40:42.
10>EnsureNode:
10>  NodeJS path is: '.bin'
10>RunNpm:
10>  ".bin\npm" install --loglevel error
10>  The system cannot find the path specified.
10>C:\JSIL\JSIL.Libraries\Targets\MSBuild.Npm.targets(11,9): error MSB3073: The command "".bin\npm" install --loglevel error" exited with code 1.
10>
10>Build FAILED.

-----------------------
The contents of npm.cmd are:

@echo off
SET PATH=%~dp0;%PATH%
SET npm_config_git=%~dp0git.cmd
"%~dp0node" "%~dp0..\..\packages\Npm.1.4.15.2\node_modules\npm\bin\npm-cli.js" %*
-----------------------

**Comment by iskiselev** [comment]
Looks like NuGet package was not restored. Could you check if there are any folder in packages that starts with NPM.*?
Please try to run command line NuGet (you can take it from https://dist.nuget.org/index.html) in root of JSIL project directory with command: NuGet restore

**Comment by iskiselev** [comment]
Close as no response was provided by @tedf619. If problem still exist, please reopen it.
