### ISSUE TITLE
JSNode reusing

### ISSUE THREAD

**Issue by iskiselev** [sq/JSIL#954]
ILBlockTranslator reuse at least JSVariable/JSIndirectVariable (through Variables/IndirectVariables dictionaries).
I used JSNode to store source mapping information, so reusing of them make such use problematically.

@kg, do you remember why you introduced such reusing? How will be better replace it?

**Comment by kg** [comment]
Mostly used for performance reasons, I think? And maybe for reference equality, but that's not really useful. I don't see any problem with just creating new instances every time as necessary.
