### ISSUE TITLE
Output failing with `Assembly has no entry point`

### ISSUE THREAD

**Issue by 0xFireball** [sq/JSIL#963]
I created a Hello World program referencing `JSIL.dll` and `JSIL.Meta.dll`.

<pre>
using System;

namespace jsiltest
{
	class Program
	{
		public static void Main(string[] args)
		{
			Console.WriteLine("Hello World!");
		}
	}
}
</pre>

I compiled it with `C:\JSIL\bin\JSILc.AnyCPU.exe --out=JSIL/ jsiltest.exe`

This gives me 4 files in my output directory, `jsiltest, Version=1.0.5938.18266, Culture=neutral, PublicKeyToken=null.js`, `jsiltest.exe.jsillog`, `jsiltest.exe.manifest.js`, and `mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.js`.

So far everything works as expected.

Finally, I created my HTML page:
<pre>
&lt;!DOCTYPE html&gt; 
&lt;html&gt;
  &lt;head&gt;
    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
  &lt;/head&gt;
  &lt;body onload=&quot;onLoad()&quot;&gt;    
    &lt;script type=&quot;text/javascript&quot;&gt;
      var jsilConfig = {
        
      };
    &lt;/script&gt;
    &lt;script src=&quot;../Libraries/JSIL.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
    
    &lt;canvas id=&quot;canvas&quot; width=&quot;1280&quot; height=&quot;720&quot;&gt;
    &lt;/canvas&gt;&lt;br&gt;

    &lt;div id=&quot;log&quot;&gt;&lt;/div&gt;

    &lt;script type=&quot;text/javascript&quot;&gt;
      function runMain () {
        var asm = JSIL.GetAssembly(&quot;jsiltest&quot;);
		JSIL.InvokeEntryPoint(asm, []);
      };
    &lt;/script&gt;
  &lt;/body&gt;
&lt;/html&gt;
</pre>

However, when I load this in the browser I get the error:

`Assembly has no entry point`

**Comment by kg** [comment]
Hi,

You didn't load your assembly.

On April 4, 2016 11:21:07 AM PDT, 0xFireball <notifications@github.com> wrote:
>I created a Hello World program referencing `JSIL.dll` and
>`JSIL.Meta.dll`.
>
><pre>
>using System;
>
>namespace jsiltest
>{
>	class Program
>	{
>		public static void Main(string[] args)
>		{
>			Console.WriteLine("Hello World!");
>		}
>	}
>}
></pre>
>
>I compiled it with `C:\JSIL\bin\JSILc.AnyCPU.exe --out=JSIL/
>jsiltest.exe`
>
>This gives me 4 files in my output directory, `jsiltest,
>Version=1.0.5938.18266, Culture=neutral, PublicKeyToken=null.js`,
>`jsiltest.exe.jsillog`, `jsiltest.exe.manifest.js`, and `mscorlib,
>Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.js`.
>
>So far everything works as expected.
>
>Finally, I created my HTML page:
><pre>
>&lt;!DOCTYPE html&gt; 
>&lt;html&gt;
>  &lt;head&gt;
>&lt;meta http-equiv=&quot;X-UA-Compatible&quot;
>content=&quot;IE=edge&quot;&gt;
>  &lt;/head&gt;
>  &lt;body onload=&quot;onLoad()&quot;&gt;    
>    &lt;script type=&quot;text/javascript&quot;&gt;
>      var jsilConfig = {
>        
>      };
>    &lt;/script&gt;
>&lt;script src=&quot;../Libraries/JSIL.js&quot;
>type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
>    
>&lt;canvas id=&quot;canvas&quot; width=&quot;1280&quot;
>height=&quot;720&quot;&gt;
>    &lt;/canvas&gt;&lt;br&gt;
>
>    &lt;div id=&quot;log&quot;&gt;&lt;/div&gt;
>
>    &lt;script type=&quot;text/javascript&quot;&gt;
>      function runMain () {
>        var asm = JSIL.GetAssembly(&quot;jsiltest&quot;);
>		JSIL.InvokeEntryPoint(asm, []);
>      };
>    &lt;/script&gt;
>  &lt;/body&gt;
>&lt;/html&gt;
></pre>
>
>However, when I load this in the browser I get the error:
>
>`Assembly has no entry point`
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/sq/JSIL/issues/963

- kg (mobile)

**Comment by 0xFireball** [comment]
Thank you for your response; however, how would I load the assembly?

**Comment by kg** [comment]
You'll need to include your assembly's manifest (generated by JSILc) in the
jsilConfig, see here:
https://github.com/sq/JSIL/wiki/jsilConfig
I'm not sure why this is missing from the wiki tutorial...

**Comment by 0xFireball** [comment]
Thanks, I got it working. This is definitely a non-issue, thanks for helping.
