### ISSUE TITLE
[Question] Custom implementations

### ISSUE THREAD

**Issue by 0xFireball** [sq/JSIL#964]
How would I write a custom implementation for classes? For example, Windows Forms, if I wanted to map the native controls to HTML elements such as buttons, inputs, etc...

**Comment by kg** [comment]
You can hand-write stubs in JS like the included ones, or you can write C# 'proxy' libraries that replace individual methods on the classes, or you can write a C# replacement for the entire library.

**Comment by 0xFireball** [comment]
Could you give a quick example? There is a large amount of source to go through...How would I write a proxy class, in particular? I am not asking for a code sample, just a more specific guide... Thanks!

**Comment by iskiselev** [comment]
You could look on Proxies.4.0 and Proxies.Bcl projects as example. Also look in wiki:https://github.com/sq/JSIL/wiki/Meta-Attributes.
Also it will be good idea to look on https://github.com/sq/JSIL/wiki/Troubleshooting-FAQ and some scripts in Libraries\IgnoredBCL folder.

**Comment by 0xFireball** [comment]
Is there an example I could look at? I really appreciate the help

**Comment by 0xFireball** [comment]
Thanks! I really appreciate the help!
