### ISSUE TITLE
[Help] Casting native JS collection to object array

### ISSUE THREAD

**Issue by 0xFireball** [sq/JSIL#966]
I am currently implementing a C# wrapper to DOM, based on [JSIL.Hacks](https://github.com/markusjohnsson/JSIL.Hacks).

I have currently encountered an issue:
I am trying to implement the property `children` of the JavaScript `element` DOM object.

My current code is:
<pre>
public Element[] Children
        {
            get
            {
                return ((object[])Verbatim.Expression("this._element.children")).Select(elementObject => GetElement(elementObject)).ToArray();
            }
        }
</pre>
(In my code, `GetElement(object)` casts a JS Dom object to the `Element` class)
However, I am getting an error that I cannot cast `System.Object` to `System.Object[]` when I cast the `Verbatim.Expression` to `object[]`. What can I do to resolve this?

**Comment by iskiselev** [comment]
You should check that `this._element.children` is really JS Array. If it is array-like object, you can try do something like `Array.prototype.slice.call(this._element.children)` before.

**Comment by 0xFireball** [comment]
Thanks, that seems to work. How would I add more complex JavaScript expressions (such as functions); is there a something like a verbatim function?

**Comment by iskiselev** [comment]
You should be able to write any JS expression, including function inside `Verbatim.Expression`.

**Comment by 0xFireball** [comment]
Thank you so much!

**Comment by kg** [comment]
FYI, there's a general 'node collection' pattern in the DOM (I forget what it's called exactly), and it has various useful methods in addition to being an array. You might just want to define a type for that with an indexer and GetEnumerator.
