### ISSUE TITLE
XAML support

### ISSUE THREAD

**Issue by 0xFireball** [sq/JSIL#969]
Is there a way I can use XAML with JSIL? I am creating a C# to HTML5 GUI framework and would like it to be usable with XAML. Currently, layouts can be built like this:

<pre>
    public class MainForm : WebForm
    {
        public MainForm()
        {
			Controls = new Layout()
        	{
        		new TextBlock()
	            {
					Text = "SharpJS WebForms Demo",
					FontStyle = new FontStyle()
					{
						FontSize = 24,
						FontWeight = JSIL.Dom.Styles.FontWeight.Bold
					},
					TextAlign = JSIL.Dom.Styles.TextAlign.Center,
				},
        		new TextBlock()
        		{
        			Text = "Enter some text:",
        		},
        		new TextBox(),
        		new Button()
        		{
        			Text = "OK",
        		},
			};
        }
    }
</pre>

I want to be able to specify this instead:
<pre>
&lt;WebForm x:Class=&quot;WebFormsTemplate.MainWFForm&quot;
	xmlns=&quot;clr-namespace:ExaPhaser.WebForms;assembly=ExaPhaser.WebForms&quot;
	xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
	xmlns:controls=&quot;clr-namespace:ExaPhaser.WebForms.Controls;assembly=ExaPhaser.WebForms&quot;&gt;
	&lt;WebForm.Controls&gt;
		&lt;controls:TextBlock Text=&quot;Hello, World!&quot; /&gt;
	&lt;/WebForm.Controls&gt;
&lt;/WebForm&gt;
</pre>

Does anyone know how I can implement this?
Please do not mention [CSHTML5](http://cshtml5.com), as it is closed source and my project is open source.

**Comment by kg** [comment]
The body of your issue seems to be mangled.

One option for XAML would be to feed the XAML through the normal MS build pipeline and translate the managed code their compiler generates. Not sure how hard that would be, though...

**Comment by 0xFireball** [comment]
I currently tried referencing `System.Xaml`, but this references all the `PresentationFramework` and `PresentationCore` assemblies, which do not seem to decompile well with JSIL. I guess I'll try writing a custom implementation or something.

**Comment by 0xFireball** [comment]
I have, however, been having trouble with the `dynamic` keyword. Is there anything special I should do when using `dynamic` with JSIL, like the `DynamicAttribute` or something?

**Comment by kg** [comment]
Yeah, I think at present you wouldn't want to cross-compile the implementation. Just cross-compile the code generated by the compiler from your XAML files. This is similar to what is done for XML Serializer assemblies.

**Comment by 0xFireball** [comment]
Is there a way I can use XAML without referencing PresentationCore and PresentationFramework? These aren't necessary but my compiler insists that I reference them.

**Comment by iskiselev** [comment]
@0xFireball. have you looked on [Fayde](http://fayde.io/) projects? They implement XAML in html on top of canvas. It  would be great if somebody would implement bindings to it, and it would be great if they will be wpf/silverlight compatible.

**Comment by iskiselev** [comment]
@0xFireball, could you describe what type of problems do you have with `dynamic`?

**Comment by iskiselev** [comment]
Also it may worth to look on https://github.com/Perspex/Perspex, it should be much easier to port it to be used with JSIL.

**Comment by 0xFireball** [comment]
Thanks! I'm trying to make an open source alternative to CSharp/Xaml for Html5

**Comment by 0xFireball** [comment]
I resolved the issue with dynamic. Sorry about that, it was bad implementation on my part.

**Comment by 0xFireball** [comment]
Hello,
if this is still relevant, I succeeded in creating a usable UI framework built upon JSIL!
https://github.com/exaphaser/SharpJS

After writing the UI framework, I wrote another library (It's [in the repo too](https://github.com/exaphaser/SharpJS/tree/master/ExaPhaser/Extensions/ExaPhaser.WebForms.Extensions.WinFormsCompat) that would allow users to port WinForms projects to the web.)

It's obviously not production ready at the moment (I didn't spend that much time on it), but it's a start
for a compatibility layer for WinForms. At the moment, you still have to recompile the project to 
reference my WinFormsCompat lib (or you could hack the assembly).

I also made C# bindings for some of jQuery (as much as the whole framework needed, I might add more)
and WebSockets, AJAX, JS Buffers, Printing, Blob saving, and uploading.

I paused development a couple months ago, but I'm restarting development again. This time, I'm going
to improve the UI framework and maybe try adding some XAML-inspired UI.

I'm looking at [Fayde](http://fayde.io/) for ideas for now.

The extensions are licensed under GPLv3 in the repository, but if a merge would help JSIL, I would be **delighted** to give the changes back to JSIL under the MIT license. Just please let me know.

**Comment by 0xFireball** [comment]
Unfortunately I messed up massively with Git, and that repo does not share a history with JSIL :( and I had to manually merge changes. That was a big mistake, but I don't want to lose my own commit history now. If anyone has a solution please let me know.

**Comment by kg** [comment]
Worst case you could generate a single massive merge commit (ugh) by doing a diff of the whole tree against JSIL. Maybe then you could split the commit up into logical chunks.
